services:
  base_postgres:
    image: postgres:16-alpine
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=pg_stat_statements",
        "-c",
        "pg_stat_statements.track=all",
        "-c",
        "pg_stat_statements.max=10000",
      ]
    hostname: base_postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_PASSWORD=password
    volumes:
      - ../storage/postgresql:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  base_ols:
    image: ghcr.io/ntj125app/frankenphp:latest
    hostname: base_ols
    ports:
      - target: 80
        published: 80
        protocol: tcp
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ../:/app
      - ../public:/app/public

  base_worker:
    image: ghcr.io/ntj125app/frankenphp:latest
    command: ["/usr/local/bin/php", "/app/artisan", "horizon"]
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ../:/app
      - ../public:/app/public

  base_scheduler:
    image: ghcr.io/ntj125app/frankenphp:latest
    command:
      [
        "/bin/sh",
        "-c",
        "/usr/local/bin/php /app/artisan system:start ; /usr/local/bin/php /app/artisan schedule:work",
      ]
    working_dir: /app
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ../:/app
      - ../public:/app/public

  base_redis:
    image: valkey/valkey:alpine
    hostname: base_redis
    command:
      [
        "redis-server",
        "--loglevel",
        "warning",
        "--stop-writes-on-bgsave-error",
        "no",
        "--maxmemory",
        "412mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ../storage/redis:/data

  base_reverb:
    image: ghcr.io/ntj125app/frankenphp:latest
    command:
      [
        "/bin/sh",
        "-c",
        "/usr/local/bin/php /app/artisan reverb:start",
      ]
    hostname: base_reverb
    working_dir: /app
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M
    ports:
      - target: 6001
        published: 6001
        protocol: tcp
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ../:/app
      - ../public:/app/public

  base_vite:
    image: ghcr.io/ntj125app/npm-custom
    command: ["pnpm", "run", "dev"]
    working_dir: /app
    ports:
      - target: 5173
        published: 5173
        protocol: tcp
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ../:/app

networks:
  default:
    name: compose-net
    attachable: true
    ipam:
      config:
        - subnet: "192.168.25.0/24"
