name: Build App Container Image for Staging

on:
    push:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    build-app: # Steps to build staging application
        runs-on: ubuntu-latest
        env:
            REGISTRY: ghcr.io # GitHub Container Registry
            IMAGE_NAME: ${{ github.repository }} # github.repository as <account>/<repo>
            ENV_BASE64: ${{ secrets.ENV_BASE64_DEV }}
        permissions:
            contents: read
            packages: write

        outputs:
            composer-cache: ${{ steps.composer-cache-dir.outputs.dir }}
            npm-cache: ${{ steps.npm-cache-dir.outputs.dir }}

        steps:
            - name: Checkout # Checkout the repository
              uses: actions/checkout@v3
            - name: Create .env file # Create .env file
              if: env.ENV_BASE64 != ''
              run: echo "$ENV_BASE64" | base64 -d > .env

            # Composer Cache
            - name: Get Composer Cache Directory
              id: composer-cache-dir
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Composer Cache
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-
            - name: Composer Install # Install composer dependencies
              run: composer install --optimize-autoloader --ignore-platform-reqs

            # NPM Cache
            - name: Set NodeJS Version # Set NodeJS Version
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Get npm cache directory
              id: npm-cache-dir
              run: |
                  echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              id: npm-cache
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: NPM CI Install # Install NPM dependencies (node_modules folder is not cached)
              run: npm ci
            - name: NPM Build # Build NPM assets
              run: npx vite build

            - name: Build Cache # Build Cache
              run: |
                  sudo mkdir -p /var/www/vhosts/localhost
                  sudo cp -a {.,}[!.]* /var/www/vhosts/localhost
                  sudo chmod -R 777 /var/www/vhosts/localhost
                  cd /var/www/vhosts/localhost
                  rm -rf $GITHUB_WORKSPACE/bootstrap/cache
                  php artisan config:cache
                  php artisan event:cache
                  php artisan route:cache
            - name: Output Cache as Artifact for volumes
              uses: actions/upload-artifact@v3
              with:
                  name: env-cache
                  path: /var/www/vhosts/localhost/bootstrap/cache
                  retention-days: 1

            - name: Setup QEMU # Setup QEMU
              uses: docker/setup-qemu-action@v2
              if: env.REGISTRY != '' && env.IMAGE_NAME != ''
            - name: Setup Docker Buildx # Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
              if: env.REGISTRY != '' && env.IMAGE_NAME != ''

            - name: Login to GitHub Container Registry # Login to GitHub Container Registry
              uses: docker/login-action@v2
              if: env.REGISTRY != '' && env.IMAGE_NAME != ''
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Get & Set Container Metadata # Get & Set Container Metadata
              id: meta-packages
              uses: docker/metadata-action@v4
              if: env.REGISTRY != '' && env.IMAGE_NAME != ''
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Clean Build App # Remove unused files & dirs
              run: rm -rf node_modules public/debug.php resources/css resources/fonts resources/images resources/js resources/vue stubs tests .git .github .gitlab .gitattributes .gitignore .vscode .editorconfig .env .env.example .styleci.yml .eslintignore .eslintrc.js .phpunit.result.cache .stylelintrc.json package.json package-lock.json pint.json tsconfig.json tsconfig.node.json *.yaml *.md *.lock *.xml *.yml *.ts *.js
            - name: Build & Push Container # Build & Push Container
              uses: docker/build-push-action@v3
              if: env.REGISTRY != '' && env.IMAGE_NAME != ''
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta-packages.outputs.tags }}-staging
                  labels: ${{ steps.meta-packages.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
